server:
  port: 5678
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: employee-service
        uri: http://localhost:7890
        predicates:
        - Path= /api/v1/employees/**
      - id: score-service
        uri: lb://service-three
        predicates:
        - Path=/api/v1/score/**
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"       
         
      