server:
  port: 7890
  
  
spring:
  application:
    name: employee-service
  config:
    import: configserver:http://localhost:8888 
  
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"