server:
  port: 7070
  ssl:
    enabled: false
    key-alias: localhost_ssl
    key-store-password: password
    key-store: classpath:localhost-ssl.p12
    key-store-type: PKCS12
  
spring:
  application:
    name: service-one
  config:
    import: configserver:http://localhost:8888  
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

